### ISSUE TITLE
View proposal/my-proposal.php could be renamed proposal/proposal.php

### ISSUE THREAD

**Issue by EmileCalixte** [alexisljn/collab-media#39]
We could use this view to display a proposal from different points of view:
- A member which displays a proposal he submitted
- A reviewer which displays a proposal he wants to review
- A publisher which displays a proposal he wants to publish

So I suggest we rename this view to use it in different actions.

**Comment by alexisljn** [comment]
Yes I suggest that we rename into "proposal.php"

**Comment by GuenoleCHERUBIN** [comment]
Yeah sounds more accurate
